//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City.Tour.Library.Models.CityTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puzzle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puzzle()
        {
            this.Hints = new HashSet<Hint>();
            this.TourPuzzles = new HashSet<TourPuzzle>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid TourId { get; set; }
        public bool IsDelete { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Sort { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string MapImage { get; set; }
        public string MapAnswer { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string MapNameImage { get; set; }
        public string Answer { get; set; }
        public string VideoContentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hint> Hints { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourPuzzle> TourPuzzles { get; set; }
    }
}
