//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City.Tour.Library.Models.CityTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime ModifyTime { get; set; }
    }
}
