//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City.Tour.Library.Models.CityTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamProgress
    {
        public System.Guid Id { get; set; }
        public System.Guid TeamId { get; set; }
        public bool IsPassMap1 { get; set; }
        public bool IsPassMap2 { get; set; }
        public bool IsPassMap3 { get; set; }
        public bool IsPassMap4 { get; set; }
        public bool IsPassMap5 { get; set; }
        public bool IsPassMap6 { get; set; }
        public bool IsPassPuzzle1 { get; set; }
        public bool IsPassPuzzle2 { get; set; }
        public bool IsPassPuzzle3 { get; set; }
        public bool IsPassPuzzle4 { get; set; }
        public bool IsPassPuzzle5 { get; set; }
        public bool IsPassPuzzle6 { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
