//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City.Tour.Library.Models.CityTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRecord
    {
        public System.Guid Id { get; set; }
        public System.Guid TeamId { get; set; }
        public System.DateTime PuzzleStartTime { get; set; }
        public Nullable<System.DateTime> PuzzleCompleteTime { get; set; }
        public bool IsPassPuzzleMap { get; set; }
        public Nullable<System.DateTime> PassPuzzleMapTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public int Sort { get; set; }
        public System.Guid TourPuzzleId { get; set; }
    
        public virtual TourPuzzle TourPuzzle { get; set; }
        public virtual Team Team { get; set; }
    }
}
