//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City.Tour.Library.Models.CityTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Puzzles = new HashSet<Puzzle>();
            this.Teams = new HashSet<Team>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public string Banner { get; set; }
        public string BannerThumb { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Info { get; set; }
        public Nullable<System.Guid> Puzzle1Id { get; set; }
        public Nullable<System.Guid> Puzzle2Id { get; set; }
        public Nullable<System.Guid> Puzzle3Id { get; set; }
        public Nullable<System.Guid> Puzzle4Id { get; set; }
        public Nullable<System.Guid> Puzzle5Id { get; set; }
        public Nullable<System.Guid> Puzzle6Id { get; set; }
        public int Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puzzle> Puzzles { get; set; }
        public virtual Puzzle Puzzle { get; set; }
        public virtual Puzzle Puzzle1 { get; set; }
        public virtual Puzzle Puzzle2 { get; set; }
        public virtual Puzzle Puzzle3 { get; set; }
        public virtual Puzzle Puzzle4 { get; set; }
        public virtual Puzzle Puzzle5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
